### ISSUE TITLE
添加清空this.queue的需求

### ISSUE THREAD

**Issue by WindomZ** [axetroy/wxapp-http#2]
**I'm submitting a ...** 

- [ ] bug report => search github for a similar issue or PR before submitting
- [x] feature request
- [ ] support request

**More detail**

- 可能对于小程序的使用场景，切换页面后是否直接清空this.queue？
- 需要判断`const entity = this.queue.shift();`不为undefined

**Comment by axetroy** [comment]
> 可能对于小程序的使用场景，切换页面后是否直接清空this.queue？

http库是独立的，不会hook进小程序的生命周期，所以没有"切换页面自动清除http队列"这样的功能

而且有一些请求不可以，比如提交表单之后，请求进入队列，如果这时候切换页面就清除队列，那么表单的请求实际上不会发出。

该不该清除队列，由开发者自己决定。0.2.0版本已经添加清空队列的方法 [Http.prototype.clean](https://github.com/axetroy/wxapp-http/blob/master/index.js#L180)

> 需要判断const entity = this.queue.shift();不为undefined

虽然Javascript是动态语言(俗称不严谨)，但是只要判断``this.queue``[有长度](https://github.com/axetroy/wxapp-http/blob/master/index.js#L61)，那么``const entity = this.queue.shift();``肯定不为undefined
